export const contactContent = {
  hero: {
    eyebrow: "CONTACT",
    title: "Book a structured IT assessment",
    subtitle:
      "Get a structured review that clarifies risk, responsibility, and practical next steps for your environment.",
    bullets: [
      "No-obligation assessment focused on operational clarity.",
      "Senior-level review of risk, scope, and priorities.",
      "Clear findings with practical recommendations and next actions.",
    ],
    primaryCta: { label: "Book a Structured IT Review", href: "/contact#assessment-form" },
    secondaryCta: { label: "View Pricing", href: "/pricing" },
  },
  process: {
    title: "What happens next?",
    subtitle: "A defined review process. Calm, structured, and outcome-focused.",
    steps: [
      {
        label: "01",
        title: "Initial call (20-30 minutes)",
        body: "We understand your current setup, priorities, and operational challenges.",
      },
      {
        label: "02",
        title: "Environment review",
        body: "High-level review of systems, security posture, documentation, and operational risk.",
      },
      {
        label: "03",
        title: "Practical recommendations",
        body: "Clear, practical recommendations with defined scope and no obligation.",
      },
    ],
  },
  form: {
    eyebrow: "REQUEST AN ASSESSMENT",
    title: "Tell us a little about your environment",
    subtitle: "A short outline is enough. We use this to understand current setup, priorities, and where structured support would help most.",
    fields: {
      name: "Full Name",
      company: "Company Name",
      industry: "Industry (optional)",
      email: "Email",
      users: "Number of Users",
      phone: "Phone",
      setup: "Current IT setup",
      goal: "Primary goal / biggest pain (optional)",
    },
    industryPlaceholder: "e.g. Construction, Finance, Retail",
    usersOptions: ["Select", "1-10", "11-25", "26-50", "51-100", "100+"],
    submitLabel: "Request IT Assessment",
    privacyNote: "Your information is confidential and never shared.",
    consentLabel: "I agree to be contacted about this assessment request.",
  },
  trustPanel: {
    eyebrow: "WHY TRIAD IT",
    title: "Why businesses choose TRIAD IT",
    intro: "The assessment is designed to reduce uncertainty, not create pressure. You get a direct review and clear next steps.",
    bullets: [
      "Direct senior review",
      "Structured next steps",
      "Security-first thinking",
      "Transparent pricing",
    ],
    closing: "Defined systems. Measured change. Controlled environments.",
    reassuranceTitle: "What to expect",
    reassuranceBody: "No hard sell. No vague next steps. Just a clear view of what matters now and what should happen next.",
  },
  direct: {
    title: "Prefer to email or call?",
    subtitle: "Contact TRIAD directly and receive a response within one business day.",
    name: "TRIAD IT",
    email: "info@triad-it.co.uk",
    phone: "0131 358 0579",
    region: "Supporting organisations across Edinburgh, Glasgow and Central Scotland.",
    reassurance: "We respond to all enquiries within one business day.",
  },
  closingCta: {
    title: "Prefer to explore first?",
    subtitle: "Review services and pricing before booking an assessment.",
    primaryLabel: "View Services",
    primaryHref: "/services",
    secondaryLabel: "View Pricing",
    secondaryHref: "/pricing",
  },
} as const;
